### ISSUE TITLE
Не давать Куде папку

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_sess_manager#1]
вы даете имя файла сессии с папкой. для Апи proc_set_session. лучше давать без пути _если_ это папка settings. тогда Куд будет portable (возьмет файл сессии в settings, если мувнуть папку Куды - так точно будет в Бете, надо проверить в релиз)

**Comment by kvichans** [comment]
Все прямо наоборот.
Пока я могу разместить и раб.файлы и файл сессии на дропбоксе и, пересаживаясь между компами, сразу (без копирования!) получать привычную среду.

**Comment by Alexey-T** [comment]
я предлагаю- чтобы Плагин **не давал в Апи папку равную settings.

**Comment by kvichans** [comment]
в чем причина такого _странного_ ограничения?

**Comment by Alexey-T** [comment]
не давайте в Апи папку равную settings. тогда сессия будет без пути- напр. "mysess.cuda-session"

это portable.

**Comment by kvichans** [comment]
я запутался
что нужно? что изменилось?

**Comment by Alexey-T** [comment]
вы даете Куде "папка_Куд/settings/mm.cuda-session"
надо давать просто "mm.cuda_session".

**Comment by kvichans** [comment]
не понимаю.
А как Куд узнает, где лежит сессия, если она не из sett?

**Comment by Alexey-T** [comment]
убирать путь *только если файл из sett.

**Comment by kvichans** [comment]
Зачем?
