### ISSUE TITLE
Session content deleted

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_sess_manager#10]
После моего пача (3 штуки) проверьте воркфлоу- у меня не работает так-

- опция Куд *reopen_ses* =false
- в плагине создал сессию через "save session as". в ней 4 файла
- закрыл-открыл Куд
- ничего не открылось и файл сессии (тот же) очистился. Т.е. файл портится

**Comment by kvichans** [comment]
Не понял, что тут **мне** проверить? Повторение проблемы? Файлы сессий пишет только Куд, я в них *ничего* не трогаю.

**Comment by kvichans** [comment]
А-а-а. После открытия без сессии - зря сохраняется пустой набор. Посмотрю, но не сегодня

**Comment by Alexey-T** [comment]
Файл пишет куд, возможно по просьбе вашего плагина

**Comment by Alexey-T** [comment]
Да, пишется в сессию просто один таю без имени

**Comment by Alexey-T** [comment]
было на моей стороне, поправил.
