### ISSUE TITLE
filter file extensions for on_open_pre

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_sess_manager#14]
мой пач который не дает дергать плагин при ненужных расширениях файлов

install.inf, ключ keys
```
[item1]
section=events
events=on_open_pre
keys=cuda-session,synw-session
```

history.txt
added: plugin now handles on_open_pre event only for session-files, ignoring other files

@kvichans

**Comment by Alexey-T** [comment]
API
1.0.321 (app 1.94.5)

    add: events on_open / on_open_pre support filtering via "keys=" in install.inf like on_key

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
ошибка дизайна - номер АПИ надо было делать как число от 1001 - счас бы было 1327

**Comment by kvichans** [comment]
Опубликовал
