### ISSUE TITLE
Cannot make new sess/ Lin

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_sess_manager#3]
Linux /Ubuntu/ "open dialog" dont allow to input name. Only choose file. I cannot make new sess in lin? 
need to
- make new session
- close all sessions (need it, for Cud dont show sess in app title)

**Comment by kvichans** [comment]
- Создать новую сессию можно командой SaveAs - получится копия текущей. Прямая команда "Создать сессию" - ToDo
- Про "закрытие всех сессий" не понял

**Comment by Alexey-T** [comment]
- Как вернуться в состояние когда Куд был без сесии(в титуле не было {dddddddd})?

**Comment by kvichans** [comment]
"Без сессии". Правильно я понимаю, что Куд не бывает "без сессии", а бывает с _умолчательной сессией_?

**Comment by Alexey-T** [comment]
Бывает,если имя_сесии пусто

**Comment by Alexey-T** [comment]
наверное да, если имя==пусто.

**Comment by kvichans** [comment]
fix
