### ISSUE TITLE
Empty name is bad

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_sess_manager#4]
Name==empty is bad: Cud looses all functions for sessions with empty name (cannot reopen tabs on start);
need name "'history session.json" (with path?)

**Comment by kvichans** [comment]
Жду. Как правильно перейти к состоянию "a la без сессии"?

**Comment by Alexey-T** [comment]
Ставьте не пусто, а см выше
В методе "закрыть сессию"
